name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo clippy --all -W clippy::all -W clippy::pedantic -W clippy::restriction -W clippy::nursery -D warnings
    - name: Run tests
      run: cargo test --verbose
